name 'cloud_linode'
maintainer 'Logan Koester'
maintainer_email 'logan@logankoester.com'
license 'mit'
description 'Installs/Configures linode'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url 'https://github.com/logankoester/chef-cloud_linode/'
issues_url 'https://github.com/logankoester/chef-cloud_linode/issues'
depends 'ohai', '>= 4.2.2'
version '0.2.0'
